services:
  fullfeedrss:
    image: "kajdo/fivefilters-full-text-rss:latest"
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=
    volumes:
      - "rss-cache:/var/www/html/cache/rss"
    ports:
      - "50000:80"
volumes:
  rss-cache:
